### ISSUE TITLE
Disable Captcha

### ISSUE THREAD

**Issue by lilyntalmers** [airform/airform#33]
**Is your feature request related to a problem? Please describe.**
I want to disable catpcha for some of my forms.

**Describe the solution you'd like**
An option to disable captcha

**Describe alternatives you've considered**

**Additional context**

**Comment by cjpatoilo** [comment]
Hi @lilyntalmers for now, it is not possible because it ensures the minimal necessary security.

Google reCAPTCHA uses an advanced risk analysis engine and adaptive challenges to keep malicious software from engaging in abusive activities on Airform.

In the future, if Airform receives investment to keep the servers running smoothly, it may become a reality.
